# Generated by Django 4.2.2 on 2023-06-14 03:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Household Name', max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 3, 6, 16, 580934, tzinfo=datetime.timezone.utc))),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 3, 6, 16, 580947, tzinfo=datetime.timezone.utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=200)),
                ('last_name', models.CharField(help_text='Last Name', max_length=200)),
                ('phone_number', models.CharField(help_text='Phone Number', max_length=255)),
                ('is_recipient', models.BooleanField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 3, 6, 16, 581205, tzinfo=datetime.timezone.utc))),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 3, 6, 16, 581273, tzinfo=datetime.timezone.utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_created_by', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 3, 6, 16, 580654, tzinfo=datetime.timezone.utc))),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 3, 6, 16, 580675, tzinfo=datetime.timezone.utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.location'),
        ),
        migrations.AddField(
            model_name='household',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office'),
        ),
    ]
