# Generated by Django 4.2.2 on 2023-06-14 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_office_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='slug',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
